### ISSUE TITLE
Playlist Parsing

### ISSUE THREAD

**Issue by GamingMidi** [monadgroup/FLParser#7]
This is more of a question than an issue. How would I go about parsing all the notes in the playlist of an flp?

**Comment by djh0ffman** [comment]
It's been a while since I worked with it so I can't remember, but there should be some clues in the below converter I made for wavesabre. I think this also deals with parts in the playlist which are clipped and looped too. 

https://github.com/logicomacorp/WaveSabre/blob/master/WaveSabreConvert/FLConverter.cs

**Comment by cpdt** [comment]
Going to close this issue now since @djh0ffman answered the question, but please let us know if you have any other questions or need more details!
